version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - netconfnetwork

  kafka1:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    hostname: kafka1
    networks:
      - netconfnetwork
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "config:1:1"
      KAFKA_DELETE_RETENTION_MS: 604800000
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 604800000
    depends_on:
      - zookeeper

  netconf-server:
    image: nexus3.onap.org:10001/onap/org.onap.integration.nfsimulator.netconfserver:1.0.0
    environment:
      - ENABLE_TLS=false
      - MODELS_CONFIGURATION_FILE_NAME=example-models-configuration.ini
    volumes:
      - ./example_models:/resources/models
      - ./example_certs:/resources/certs
    networks:
      - netconfnetwork
    ports:
      - "830:830"
      - "6513:6513"
      - "6555:6555"
    depends_on:
      - zookeeper
      - kafka1

  filezilla_ftp_client:
    image: jlesage/filezilla
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/filezilla:/config:rw"
      - "./filezila_files:/storage:rw"
    restart: on-failure
  
  sftp:
    image: atmoz/sftp:latest
    volumes:
        - ./upload:/home/foo/upload
    ports:
        - "2222:22"
    command: foo:pass:1001:100:upload

networks:
  netconfnetwork:
    driver: bridge
